Brush graph update 1
altibiz/ozds pull request #113
Opened 2024-09-19 10:43 UTC by GabrijelAB

# Task

@HrvojeJuric

Fixes #109.

## Description

Fixed date issue, added brush graph to meter details page

## Testing

N/A

## Documentation

N/A

2024-09-25 06:06 UTC, HrvojeJuric requested changes
pls sam kad radis ove time funkcije pls dodaj i testove barem - malo mi je tesko skuzit tocno sto radi funkcija iz naslova pa zto molim pls i docs

2024-09-25 11:18 UTC, GabrijelAB commented on src/Ozds.Business/Time/DateTimeOffsetExtensions.cs
> +  public static DateTimeOffset GetStartOfNextMonthNoTransformation(
Može, nisam dodao jer sam uoćio da ni druge "NoTransformation" metode nemaju testiranje. 
Budem za sve onda dodao ! 
Taj no transform je bez bilokakvih date offseta, bitno kada frontent treba prikazat tipa 1.9. 00:00:00 al se u bazi zaprvo šalje 31.8. 23:00:00. Tipa na grafu, poćetak mjeseca, treba biti prikazano piše bez offseta.

2024-09-25 11:23 UTC, HrvojeJuric commented on src/Ozds.Business/Time/DateTimeOffsetExtensions.cs
> +  public static DateTimeOffset GetStartOfNextMonthNoTransformation(
me zapravo nebi trebali imati te metode uopce sad kad vidim kaj rade
aj u call ostani pls nakon

2024-09-25 12:18 UTC, HrvojeJuric commented
[InlineData(
    "2024-03-31T23:38:56Z",
    "2024-03-31T23:00:00Z")] // Leap year, CET offset is +1
    
ovo treba proc za GetStartOfMonth
isti ovakvi testovi gdje je unasoj zoni jedan mjesec a u utc drugi i prema tome nam da krivi datum bi trebali radit
maknut
dakle sve NoTransformation metode maknut
i zamjenit sa vec postojecim koje rade

2024-10-01 09:14 UTC, GabrijelAB reviewed
Added testing, fixed time edge issue, replaced NoTransform methods with correct DateTime alteration where needed

2024-10-02 12:34 UTC, merged